version: '3.3'
services:
  alfieri-test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "file:/app/dev.db"
        DATABASE_PATH: "/app/dev.db"
    command:
      - npm
      - run
      - start
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_ENDPOINT: 'http://localhost:3000/api'
      DATABASE_URL: "file:/app/dev.db"
      NODE_ENV: 'production'
    ports:
      - '3000:3000'
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          cpus: '1.0'
          memory: 1024M
        limits:
          cpus: '1.0'
          memory: 1024M
